### ISSUE TITLE
Pebble Time Round

### ISSUE THREAD

**Issue by RetepV** [cpfair/pTOTP#10]
I used to be able to use the app on my Pebble Time Round. But today I tried to reinstall it, and the installer tells me that the app is not compatible with the Pebble Time Round.

I recently switched from the Pebble servers to the Rebble servers. Could that be the problem?

The app installed and works fine on my regular Pebble Time. And it worked fine on my Time Round before. Just that on the Time Round it eats a lot of battery power. :)

**Comment by cpfair** [comment]
This is likely an issue with the Rebble app store. Maybe try  installing the PBW directly: https://pbws.rebble.io/pbw/576d36d78d1372eef80001d0.pbw, or reinstalling the Pebble phone app.
